### ISSUE TITLE
SCSS support

### ISSUE THREAD

**Issue by cristian-sima** [Siilwyn/css-declaration-sorter-atom#1]
Can you add scss support?

**Comment by Siilwyn** [comment]
It will be in the future, because SCSS supports nested selectors this is related to another issue. Once [this issue](https://github.com/Siilwyn/css-declaration-sorter/issues/6) on the core is solved it will be possible.

**Comment by cristian-sima** [comment]
Thanks for your quick response.

I wait for it

**Comment by codefocus** [comment]
Would be awesome to have SCSS support :)

**Comment by Siilwyn** [comment]
As of version 0.3.0 the package supports SCSS and Less. :tada: 

If you find this useful please consider retweeting my announcement:
https://twitter.com/Siilwyn/status/761565830010331136

**Comment by alexandremagro** [comment]
Will SASS files be supported or not intended?
