### ISSUE TITLE
Sorting destroys css

### ISSUE THREAD

**Issue by Fbetz** [Siilwyn/css-declaration-sorter-atom#104]
The simple css

body {
    display: block;
    animation: none;
    color: #C55;
    border: 0;
}

After sorting i get

body {
    animation: none;
    border: 0;

    display: block;
none;
    color: #C55;
    border: 0;
}

**Comment by vishnupneel** [comment]
Same issue for me too.

**Comment by Siilwyn** [comment]
PR is welcome!

**Comment by ClemensSahs** [comment]
is this fixed? I don't can repo this one?

**Comment by Siilwyn** [comment]
Can't reproduce this either.
