### ISSUE TITLE
test dont work correct

### ISSUE THREAD

**Issue by ClemensSahs** [Siilwyn/css-declaration-sorter-atom#110]
current the test don't work. put this line into it
```javascript
expect(editor.getText()).toBe('test');
``` 

https://github.com/Siilwyn/css-declaration-sorter-atom/blob/master/spec/main-spec.js#L42
https://github.com/Siilwyn/css-declaration-sorter-atom/blob/master/spec/main-spec.js#L53
https://github.com/Siilwyn/css-declaration-sorter-atom/blob/master/spec/main-spec.js#L65

**Comment by Siilwyn** [comment]
You're right, they did work some months ago but I guess with the new Atom version it doesn't anymore...
I've spend hours and hours on these tests, writing Atom tests sucks in my experience, do you perhaps know what's going on?

I actually don't use Atom anymore, would you like to take on maintenance on this package? Awesome to see your PR's #108 & #109! :partying_face:

**Comment by ClemensSahs** [comment]
Currently not I not in the setTimeout function never runs correct in my mind.

I think the problem ist to get a promise for the change.

Sorry #108 is not from me ;)

Perhapse later we can take over the point maintenance, first I muss find the test problem ;)

**Comment by Siilwyn** [comment]
I've fixed the tests execution!
