### ISSUE TITLE
Format on save option

### ISSUE THREAD

**Issue by thyagorafaell** [Siilwyn/css-declaration-sorter-atom#24]
It would be nice if the plugin were run after save the file, as other packages do.

**Comment by Siilwyn** [comment]
Yes that would be great! If I find time for it I'll make it happen. PR for this is welcome too!

**Comment by generator85** [comment]
This would be awesome!

**Comment by Siilwyn** [comment]
Do you think adding this option is worth an increase of 200ms in startup time?

**Comment by Siilwyn** [comment]
Added in version 1.2.0!
