### ISSUE TITLE
Sorting CSS parsing error

### ISSUE THREAD

**Issue by oxk4r01** [Siilwyn/css-declaration-sorter-atom#36]
![image](https://cloud.githubusercontent.com/assets/1032224/26645801/ad73090e-4639-11e7-8114-c4ab7eb70e37.png)
I got that error when choose SMACSS or concentric CSS.  
Thanks in advance

**Comment by Siilwyn** [comment]
That's odd, could you try re-installing the package?

**Comment by oxk4r01** [comment]
Yes, but same results. Maybe the accent in the route could be the culprit?

**Comment by Siilwyn** [comment]
:thinking: shouldn't be, could you check if the file (and enclosing directories exist)?

**Comment by oxk4r01** [comment]
I reinstalled and is solved. Don't know why it happened, but now it's everthing ok. BTW could it be possible in future releases add an option for sort selection, or for avoid the sorting of some selectors? I accustom to place comments above the @font-face selector, and the plugin sends them to the bottom...

**Comment by Siilwyn** [comment]
Sorting the selected code might be a good addition to the plugin. However it shouldn't move the comments like that in the first place, could you give example CSS input, output and expected output?

**Comment by Siilwyn** [comment]
I found the culprit and will push the fix soon. The first comment is not detected as a newline comment because it's the first line in the file, if you add an empty line before it it will work as expected.

**Comment by Siilwyn** [comment]
https://github.com/Siilwyn/css-declaration-sorter/issues/37
