### ISSUE TITLE
Custom Order Rules

### ISSUE THREAD

**Issue by AdamMarsden** [Siilwyn/css-declaration-sorter-atom#49]
It would be cool if we were able to add custom order rules instead of only the default 3.

**Comment by AdamMarsden** [comment]
@Siilwyn Anything on this? 😊

**Comment by Siilwyn** [comment]
Hi, excuse me for not responding. I was in a very busy period when this issue got opened. Not sure if I can add this soon so feel free to open a PR!

Note that it is already possible by using the [css-declaration-sorter](https://github.com/Siilwyn/css-declaration-sorter#readme) directly, I'm curious: what do you want to use this for?

**Comment by AdamMarsden** [comment]
Just to be able to do it right inside Atom would be great, that's the only reason really!

I'm just using https://github.com/csscomb/csscomb.js instead now, thanks!

**Comment by Siilwyn** [comment]
All right!
