### ISSUE TITLE
Z-index not placed in correct position

### ISSUE THREAD

**Issue by generator85** [Siilwyn/css-declaration-sorter-atom#62]
For some reason the property "z-index" gets moved to the bottom of every declaration. I've checked the "css-property-sort-order-smacss" package inside my node_modules, and z-index is defined where it should be; between "position" and "top". 

Any idea what could be causing this?

**Comment by Siilwyn** [comment]
Hi there that package is not related and not used by this module. This [JSON file](https://github.com/Siilwyn/css-declaration-sorter/blob/master/orders/smacss.json) contains the order for SMACSS where `z-index` is at the bottom. Do you expect this property to be included in the 'Box' section? Please create an issue at the core module if so: https://github.com/Siilwyn/css-declaration-sorter
