### ISSUE TITLE
Applying a diff instead of replacing the entire file

### ISSUE THREAD

**Issue by aleclarson** [Siilwyn/css-declaration-sorter-atom#72]
When using `setText`, the undo/redo history gets really messed up.

I think you'll find [this commit](https://github.com/aleclarson/atom-css-concentric-sort/commit/af6ea1aebab98e99b48c6cb9175272fefbed30b6) very useful in fixing that.

I would send a pull request, but I'm using [my own fork](https://github.com/aleclarson/atom-css-concentric-sort) instead.

**Comment by Siilwyn** [comment]
Oh very interesting, great to see! Could you explain what you mean with "history gets really messed up"? When I'm using Atom undoing and redoing work fine.

Sidenote: did you test the performance of replacing the diff on large files?

**Comment by aleclarson** [comment]
Oh, you know what. I was tricked by another bug in your package. While making other changes, [the text-buffer listeners](https://github.com/Siilwyn/css-declaration-sorter-atom/blob/master/lib/css-declaration-sorter.js#L85) weren't being cleaned up when deactivating/re-activating the package. This lead to multiple "undo points" that did nothing, leading me to believe the package was *super* flawed!

But this change is still nice, because if you do undo/redo after formatting, your cursor isn't moved to the bottom of the file. 😄

As for performance, I don't have any huge CSS files on hand to test it. If I were to guess, I'd say the re-rendering of the entire file is more expensive than 100's of tiny re-renders. I could be wrong, or maybe there's no noticeable difference in that regard. 🤷🏼‍♂️

**Comment by aleclarson** [comment]
I just noticed [diff](https://npmjs.org/package/diff) is pretty heavy. You'd probably want to use [line-diff](https://github.com/IonicaBizau/node-line-diff) instead, since that's the only functionality you need.

**Comment by Siilwyn** [comment]
Thank you for your detailed reply! Sorry about the late response, I'm working on one and a thousand things... When I find time I'll look into creating a 'diff' and applying it.

For now I pushed a new patch version to fix 'undo points' from stacking up when there is no change made.

**Comment by Siilwyn** [comment]
Thank you for the idea and initial implementation! :heart:
