### ISSUE TITLE
Prevents saving trailing new line at end file

### ISSUE THREAD

**Issue by Otterpocket** [Siilwyn/css-declaration-sorter-atom#80]
When setting the "Format on save" option the package will sometimes delete the blank newline at the end of the file.

**Comment by Otterpocket** [comment]
So with the default settings in atom saving a file without a trailing new line will cause atom to add the new line and then save (provided by the native whitespace package).
With css-declaration-sorter-atom if I remove then trailing new line, the new line is not added when the file is saved.

**Comment by Siilwyn** [comment]
As a side-effect of applying changes per line this issue should be solved. Thank you for your feedback!
